Feature/change models naming
Finka95/PV pull request #12
Opened 2024-06-18 12:07 UTC by VladPristavkin

2024-06-19 14:40 UTC, Finka95 requested changes

2024-06-19 14:40 UTC, Finka95 commented on HealthMate/HealthMate.API/Abstractions/IGenericController.cs
>          public Task<TDto?> GetByIdAsync(Guid id, CancellationToken token);
public

2024-06-19 14:40 UTC, Finka95 commented on HealthMate/HealthMate.API/ViewModels/Mood/MoodViewModel.cs
> +        public MoodStatus MoodStatus { get; set; } = MoodStatus.Unselected;
As I know, model will create with first option in MoodStatus

2024-06-19 14:40 UTC, Finka95 commented on HealthMate/HealthMate.DAL/Entities/MedicationEntity.cs
> +        public string MedicationName { get; set; } = string.Empty; //Name of the medication
You can keep comments in BLL layer only

2024-06-19 14:54 UTC, Finka95 approved these changes

2024-06-20 07:37 UTC, DarPers approved these changes

2024-06-20 07:38 UTC, merged